version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sqlserverdata:/var/opt/mssql

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi
    environment:
      - ConnectionStrings__SqlServer=Server=sqlserver;Database=TransferenciaDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true;Encrypt=false
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserverdata:
